@startuml

class HttpClient #F08080
interface IHttpClientFactory {
  CreateClient(string name)
}
class DefaultHttpClientFactory #3CB371

abstract HttpMessageHandler #00FFFF
abstract DelegatingHandler #00FFFF
class HttpClientHandler #00FFFF
class SocketsHttpHandler #00FFFF
class LifetimeTrackingHttpMessageHandler #00FFFF


abstract HttpMessageHandlerBuilder
class DefaultHttpMessageHandlerBuilder
interface IHttpMessageHandlerBuilderFilter #3CB371
class LoggingHttpMessageHandlerBuilderFilter

class ActiveHandlerTrackingEntry #3CB371
class ExpiredHandlerTrackingEntry #3CB371
class WeakReference

class HttpClientFactoryOptions #3CB371{
  List<Action<HttpClient>> HttpClientActions
  List<Action<HttpMessageHandlerBuilder>> HttpMessageHandlerBuilderActions
  TimeSpan HandlerLifetime
}

interface IServiceScope
note bottom of IServiceScope : is scope in which pipeline is built

note right of DefaultHttpClientFactory : is registered as Singleton

note right of LifetimeTrackingHttpMessageHandler : is outmost handler in pipeline
note "are primary handlers.\nActually make socket connection\nand send request" as N1
HttpClientHandler .up. N1 : .NET Core 2.0 and earlier
N1 .. SocketsHttpHandler : since .NET Core 2.1

note bottom of LoggingHttpMessageHandlerBuilderFilter : is registered by default

DefaultHttpClientFactory -up-|> IHttpClientFactory
DefaultHttpClientFactory o-- HttpClientFactoryOptions
DefaultHttpClientFactory o-- "1..*" IHttpMessageHandlerBuilderFilter
DefaultHttpClientFactory o-- "1..*" ActiveHandlerTrackingEntry : contains\ndictionary\n(key is name)\nof
DefaultHttpClientFactory o-- "1..*" ExpiredHandlerTrackingEntry : contains queue of
DefaultHttpClientFactory --> IServiceScope : disposes after there\nisn't any reference\nto expired handler
LoggingHttpMessageHandlerBuilderFilter -up-|> IHttpMessageHandlerBuilderFilter

ActiveHandlerTrackingEntry --> LifetimeTrackingHttpMessageHandler : tracks when expired
ActiveHandlerTrackingEntry o-- IServiceScope
ActiveHandlerTrackingEntry -right-> ExpiredHandlerTrackingEntry : is replaces after timer expired by
ExpiredHandlerTrackingEntry o-- IServiceScope
ExpiredHandlerTrackingEntry o-- WeakReference : has
WeakReference --> LifetimeTrackingHttpMessageHandler : of
HttpMessageHandlerBuilder --> IServiceScope : is created in

DelegatingHandler --|> HttpMessageHandler
HttpClientHandler --|> HttpMessageHandler
SocketsHttpHandler --|> HttpMessageHandler
LifetimeTrackingHttpMessageHandler --|> DelegatingHandler


HttpClientFactoryOptions --> HttpClient : contains actions\nto configure
HttpClientFactoryOptions --> HttpMessageHandlerBuilder : contains actions\nto configure
HttpClientFactoryOptions -right-> ActiveHandlerTrackingEntry : contains\nlifetime of

DefaultHttpMessageHandlerBuilder -up-|> HttpMessageHandlerBuilder
HttpMessageHandlerBuilder --> HttpMessageHandler : builds
IHttpMessageHandlerBuilderFilter --> HttpMessageHandlerBuilder : is action to configure\n(right before Build() is called)

@enduml

